<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUkgl3xq\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUkgl3xq/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerUkgl3xq.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerUkgl3xq\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerUkgl3xq\appProdProjectContainer([
    'container.build_hash' => 'Ukgl3xq',
    'container.build_id' => '98181638',
    'container.build_time' => 1764985468,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUkgl3xq');
