<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerElj7jpa\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerElj7jpa/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerElj7jpa.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerElj7jpa\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerElj7jpa\appProdProjectContainer([
    'container.build_hash' => 'Elj7jpa',
    'container.build_id' => 'a5466ade',
    'container.build_time' => 1765036513,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerElj7jpa');
