<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PsCheckout\Api\Http\CheckoutHttpClient' shared service.

return $this->services['PsCheckout\\Api\\Http\\CheckoutHttpClient'] = new \PsCheckout\Api\Http\CheckoutHttpClient(${($_ = isset($this->services['PsCheckout\\Api\\Http\\Configuration\\CheckoutClientConfigurationBuilder']) ? $this->services['PsCheckout\\Api\\Http\\Configuration\\CheckoutClientConfigurationBuilder'] : $this->load('getCheckoutClientConfigurationBuilderService.php')) && false ?: '_'});
