<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PsCheckout\Core\OrderState\Action\ChangeOrderStateAction' shared service.

return $this->services['PsCheckout\\Core\\OrderState\\Action\\ChangeOrderStateAction'] = new \PsCheckout\Core\OrderState\Action\ChangeOrderStateAction(${($_ = isset($this->services['PsCheckout\\Infrastructure\\Repository\\OrderRepository']) ? $this->services['PsCheckout\\Infrastructure\\Repository\\OrderRepository'] : ($this->services['PsCheckout\\Infrastructure\\Repository\\OrderRepository'] = new \PsCheckout\Infrastructure\Repository\OrderRepository())) && false ?: '_'}, ${($_ = isset($this->services['PsCheckout\\Infrastructure\\Repository\\OrderStateRepository']) ? $this->services['PsCheckout\\Infrastructure\\Repository\\OrderStateRepository'] : ($this->services['PsCheckout\\Infrastructure\\Repository\\OrderStateRepository'] = new \PsCheckout\Infrastructure\Repository\OrderStateRepository())) && false ?: '_'}, ${($_ = isset($this->services['PsCheckout\\Infrastructure\\Repository\\OrderHistoryRepository']) ? $this->services['PsCheckout\\Infrastructure\\Repository\\OrderHistoryRepository'] : ($this->services['PsCheckout\\Infrastructure\\Repository\\OrderHistoryRepository'] = new \PsCheckout\Infrastructure\Repository\OrderHistoryRepository())) && false ?: '_'});
