<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PsCheckout\Infrastructure\Bootstrap\Install\CompatibilityRulesInstaller' shared service.

return $this->services['PsCheckout\\Infrastructure\\Bootstrap\\Install\\CompatibilityRulesInstaller'] = new \PsCheckout\Infrastructure\Bootstrap\Install\CompatibilityRulesInstaller(${($_ = isset($this->services['PsCheckout\\Infrastructure\\Repository\\CountryRepository']) ? $this->services['PsCheckout\\Infrastructure\\Repository\\CountryRepository'] : $this->load('getCountryRepository2Service.php')) && false ?: '_'}, ${($_ = isset($this->services['PsCheckout\\Infrastructure\\Repository\\CurrencyRepository']) ? $this->services['PsCheckout\\Infrastructure\\Repository\\CurrencyRepository'] : $this->load('getCurrencyRepository2Service.php')) && false ?: '_'});
