<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PsCheckout\Presentation\Presenter\FundingSource\FundingSourcePresenter' shared service.

return $this->services['PsCheckout\\Presentation\\Presenter\\FundingSource\\FundingSourcePresenter'] = new \PsCheckout\Presentation\Presenter\FundingSource\FundingSourcePresenter(${($_ = isset($this->services['ps_checkout.module']) ? $this->services['ps_checkout.module'] : $this->load('getPsCheckout_ModuleService.php')) && false ?: '_'}->getPathUri(), ${($_ = isset($this->services['PsCheckout\\Infrastructure\\Repository\\FundingSourceRepository']) ? $this->services['PsCheckout\\Infrastructure\\Repository\\FundingSourceRepository'] : $this->load('getFundingSourceRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['PsCheckout\\Presentation\\Presenter\\FundingSource\\FundingSourceTranslationProvider']) ? $this->services['PsCheckout\\Presentation\\Presenter\\FundingSource\\FundingSourceTranslationProvider'] : $this->load('getFundingSourceTranslationProviderService.php')) && false ?: '_'});
