<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PsCheckout\Core\FundingSource\Factory\FundingSourceTokenFactory' shared service.

return $this->services['PsCheckout\\Core\\FundingSource\\Factory\\FundingSourceTokenFactory'] = new \PsCheckout\Core\FundingSource\Factory\FundingSourceTokenFactory(${($_ = isset($this->services['PsCheckout\\Presentation\\Presenter\\FundingSource\\FundingSourceTranslationProvider']) ? $this->services['PsCheckout\\Presentation\\Presenter\\FundingSource\\FundingSourceTranslationProvider'] : $this->load('getFundingSourceTranslationProviderService.php')) && false ?: '_'}, ${($_ = isset($this->services['PsCheckout\\Presentation\\Presenter\\FundingSource\\LogoPresenter']) ? $this->services['PsCheckout\\Presentation\\Presenter\\FundingSource\\LogoPresenter'] : $this->load('getLogoPresenterService.php')) && false ?: '_'});
