<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PsCheckout\Presentation\Presenter\FundingSource\FundingSourceTokenPresenter' shared service.

return $this->services['PsCheckout\\Presentation\\Presenter\\FundingSource\\FundingSourceTokenPresenter'] = new \PsCheckout\Presentation\Presenter\FundingSource\FundingSourceTokenPresenter(${($_ = isset($this->services['PsCheckout\\Infrastructure\\Repository\\PaymentTokenRepository']) ? $this->services['PsCheckout\\Infrastructure\\Repository\\PaymentTokenRepository'] : $this->load('getPaymentTokenRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['PsCheckout\\Infrastructure\\Adapter\\Configuration']) ? $this->services['PsCheckout\\Infrastructure\\Adapter\\Configuration'] : $this->load('getConfigurationService.php')) && false ?: '_'}, ${($_ = isset($this->services['PsCheckout\\Core\\FundingSource\\Factory\\FundingSourceTokenFactory']) ? $this->services['PsCheckout\\Core\\FundingSource\\Factory\\FundingSourceTokenFactory'] : $this->load('getFundingSourceTokenFactoryService.php')) && false ?: '_'});
