<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PsCheckout\Core\Order\Builder\Node\GooglePayPaymentSourceNodeBuilder' shared service.

return $this->services['PsCheckout\\Core\\Order\\Builder\\Node\\GooglePayPaymentSourceNodeBuilder'] = new \PsCheckout\Core\Order\Builder\Node\GooglePayPaymentSourceNodeBuilder(${($_ = isset($this->services['PsCheckout\\Core\\Settings\\Configuration\\PayPalConfiguration']) ? $this->services['PsCheckout\\Core\\Settings\\Configuration\\PayPalConfiguration'] : $this->load('getPayPalConfigurationService.php')) && false ?: '_'});
