<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PsCheckout\Core\PayPal\ShippingTracking\Validator\OrderTrackerValidator' shared service.

return $this->services['PsCheckout\\Core\\PayPal\\ShippingTracking\\Validator\\OrderTrackerValidator'] = new \PsCheckout\Core\PayPal\ShippingTracking\Validator\OrderTrackerValidator(${($_ = isset($this->services['PsCheckout\\Infrastructure\\Repository\\PayPalOrderRepository']) ? $this->services['PsCheckout\\Infrastructure\\Repository\\PayPalOrderRepository'] : $this->load('getPayPalOrderRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['PsCheckout\\Infrastructure\\Repository\\PayPalOrderCaptureRepository']) ? $this->services['PsCheckout\\Infrastructure\\Repository\\PayPalOrderCaptureRepository'] : $this->load('getPayPalOrderCaptureRepositoryService.php')) && false ?: '_'});
