<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PsCheckout\Api\Http\OrderHttpClient' shared service.

return $this->services['PsCheckout\\Api\\Http\\OrderHttpClient'] = new \PsCheckout\Api\Http\OrderHttpClient(${($_ = isset($this->services['PsCheckout\\Api\\Http\\Configuration\\OrderHttpClientConfigurationBuilder']) ? $this->services['PsCheckout\\Api\\Http\\Configuration\\OrderHttpClientConfigurationBuilder'] : $this->load('getOrderHttpClientConfigurationBuilderService.php')) && false ?: '_'});
