<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PsCheckout\Core\PayPal\Order\Cache\PayPalOrderCache' shared service.

return $this->services['PsCheckout\\Core\\PayPal\\Order\\Cache\\PayPalOrderCache'] = new \PsCheckout\Core\PayPal\Order\Cache\PayPalOrderCache(${($_ = isset($this->services['PsCheckout\\Cache\\Array\\PayPalOrder']) ? $this->services['PsCheckout\\Cache\\Array\\PayPalOrder'] : ($this->services['PsCheckout\\Cache\\Array\\PayPalOrder'] = new \Symfony\Component\Cache\Adapter\ArrayAdapter())) && false ?: '_'}, ${($_ = isset($this->services['PsCheckout\\Cache\\FileSystem\\PayPalOrder']) ? $this->services['PsCheckout\\Cache\\FileSystem\\PayPalOrder'] : $this->load('getPayPalOrder2Service.php')) && false ?: '_'}, ${($_ = isset($this->services['PsCheckout\\Core\\PayPal\\OrderStatus\\Action\\PayPalCheckOrderStatusAction']) ? $this->services['PsCheckout\\Core\\PayPal\\OrderStatus\\Action\\PayPalCheckOrderStatusAction'] : ($this->services['PsCheckout\\Core\\PayPal\\OrderStatus\\Action\\PayPalCheckOrderStatusAction'] = new \PsCheckout\Core\PayPal\OrderStatus\Action\PayPalCheckOrderStatusAction())) && false ?: '_'});
