<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PsCheckout\Core\Settings\Configuration\PayPalConfiguration' shared service.

return $this->services['PsCheckout\\Core\\Settings\\Configuration\\PayPalConfiguration'] = new \PsCheckout\Core\Settings\Configuration\PayPalConfiguration(${($_ = isset($this->services['PsCheckout\\Infrastructure\\Adapter\\Configuration']) ? $this->services['PsCheckout\\Infrastructure\\Adapter\\Configuration'] : $this->load('getConfigurationService.php')) && false ?: '_'});
