<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PsCheckout\Presentation\Presenter\Settings\Admin\Modules\PaypalModule' shared service.

return $this->services['PsCheckout\\Presentation\\Presenter\\Settings\\Admin\\Modules\\PaypalModule'] = new \PsCheckout\Presentation\Presenter\Settings\Admin\Modules\PaypalModule(${($_ = isset($this->services['PsCheckout\\Infrastructure\\Adapter\\Configuration']) ? $this->services['PsCheckout\\Infrastructure\\Adapter\\Configuration'] : $this->load('getConfigurationService.php')) && false ?: '_'});
