<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PsCheckout\Presentation\Presenter\PayPalOrder\PayPalOrderTotalsPresenter' shared service.

return $this->services['PsCheckout\\Presentation\\Presenter\\PayPalOrder\\PayPalOrderTotalsPresenter'] = new \PsCheckout\Presentation\Presenter\PayPalOrder\PayPalOrderTotalsPresenter();
