<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PsCheckout\Presentation\Presenter\PayPalOrder\PayPalOrderTransactionPresenter' shared service.

return $this->services['PsCheckout\\Presentation\\Presenter\\PayPalOrder\\PayPalOrderTransactionPresenter'] = new \PsCheckout\Presentation\Presenter\PayPalOrder\PayPalOrderTransactionPresenter(${($_ = isset($this->services['PsCheckout\\Presentation\\Presenter\\Date\\DatePresenter']) ? $this->services['PsCheckout\\Presentation\\Presenter\\Date\\DatePresenter'] : $this->load('getDatePresenterService.php')) && false ?: '_'}, ${($_ = isset($this->services['PsCheckout\\Module\\Presentation\\Translator']) ? $this->services['PsCheckout\\Module\\Presentation\\Translator'] : $this->load('getTranslatorService.php')) && false ?: '_'});
