<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PsCheckout\Core\PayPal\Order\Action\RefundPayPalOrderAction' shared service.

return $this->services['PsCheckout\\Core\\PayPal\\Order\\Action\\RefundPayPalOrderAction'] = new \PsCheckout\Core\PayPal\Order\Action\RefundPayPalOrderAction(${($_ = isset($this->services['PsCheckout\\Infrastructure\\Adapter\\Configuration']) ? $this->services['PsCheckout\\Infrastructure\\Adapter\\Configuration'] : $this->load('getConfigurationService.php')) && false ?: '_'}, ${($_ = isset($this->services['PsCheckout\\Api\\Http\\OrderHttpClient']) ? $this->services['PsCheckout\\Api\\Http\\OrderHttpClient'] : $this->load('getOrderHttpClientService.php')) && false ?: '_'}, ${($_ = isset($this->services['PsCheckout\\Core\\OrderState\\Action\\SetRefundedOrderStateAction']) ? $this->services['PsCheckout\\Core\\OrderState\\Action\\SetRefundedOrderStateAction'] : $this->load('getSetRefundedOrderStateActionService.php')) && false ?: '_'});
