<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PsCheckout\Infrastructure\Action\SaveBatchConfigurationActionInterface' shared service.

return $this->services['PsCheckout\\Infrastructure\\Action\\SaveBatchConfigurationActionInterface'] = new \PsCheckout\Infrastructure\Action\SaveBatchConfigurationAction(${($_ = isset($this->services['PsCheckout\\Infrastructure\\Adapter\\Configuration']) ? $this->services['PsCheckout\\Infrastructure\\Adapter\\Configuration'] : $this->load('getConfigurationService.php')) && false ?: '_'});
