<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PsCheckout\Core\PayPal\ShippingTracking\Cache\ShippingTrackingCache' shared service.

return $this->services['PsCheckout\\Core\\PayPal\\ShippingTracking\\Cache\\ShippingTrackingCache'] = new \PsCheckout\Core\PayPal\ShippingTracking\Cache\ShippingTrackingCache(${($_ = isset($this->services['PsCheckout\\Cache\\Array\\ShippingTracking']) ? $this->services['PsCheckout\\Cache\\Array\\ShippingTracking'] : ($this->services['PsCheckout\\Cache\\Array\\ShippingTracking'] = new \Symfony\Component\Cache\Adapter\ArrayAdapter())) && false ?: '_'}, ${($_ = isset($this->services['PsCheckout\\Cache\\FileSystem\\ShippingTracking']) ? $this->services['PsCheckout\\Cache\\FileSystem\\ShippingTracking'] : $this->load('getShippingTracking2Service.php')) && false ?: '_'});
