<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PsCheckout\Core\PayPal\ShippingTracking\Service\TrackingApiService' shared service.

return $this->services['PsCheckout\\Core\\PayPal\\ShippingTracking\\Service\\TrackingApiService'] = new \PsCheckout\Core\PayPal\ShippingTracking\Service\TrackingApiService(${($_ = isset($this->services['PsCheckout\\Api\\Http\\OrderShipmentTrackingHttpClient']) ? $this->services['PsCheckout\\Api\\Http\\OrderShipmentTrackingHttpClient'] : $this->load('getOrderShipmentTrackingHttpClientService.php')) && false ?: '_'}, ${($_ = isset($this->services['logger']) ? $this->services['logger'] : $this->getLoggerService()) && false ?: '_'});
