<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PsCheckout\Core\PayPal\Order\Action\UpdatePayPalOrderPurchaseUnitAction' shared service.

return $this->services['PsCheckout\\Core\\PayPal\\Order\\Action\\UpdatePayPalOrderPurchaseUnitAction'] = new \PsCheckout\Core\PayPal\Order\Action\UpdatePayPalOrderPurchaseUnitAction(${($_ = isset($this->services['PsCheckout\\Infrastructure\\Repository\\PayPalOrderPurchaseUnitRepository']) ? $this->services['PsCheckout\\Infrastructure\\Repository\\PayPalOrderPurchaseUnitRepository'] : $this->load('getPayPalOrderPurchaseUnitRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['PsCheckout\\Infrastructure\\Repository\\PayPalOrderCaptureRepository']) ? $this->services['PsCheckout\\Infrastructure\\Repository\\PayPalOrderCaptureRepository'] : $this->load('getPayPalOrderCaptureRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['PsCheckout\\Infrastructure\\Repository\\PayPalOrderAuthorizationRepository']) ? $this->services['PsCheckout\\Infrastructure\\Repository\\PayPalOrderAuthorizationRepository'] : $this->load('getPayPalOrderAuthorizationRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['PsCheckout\\Infrastructure\\Repository\\PayPalOrderRefundRepository']) ? $this->services['PsCheckout\\Infrastructure\\Repository\\PayPalOrderRefundRepository'] : $this->load('getPayPalOrderRefundRepositoryService.php')) && false ?: '_'});
