<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PsCheckout\Infrastructure\Bootstrap\Install\ApplePayInstaller' shared service.

return $this->services['PsCheckout\\Infrastructure\\Bootstrap\\Install\\ApplePayInstaller'] = new \PsCheckout\Infrastructure\Bootstrap\Install\ApplePayInstaller(${($_ = isset($this->services['PsCheckout\\Infrastructure\\Adapter\\SystemConfiguration']) ? $this->services['PsCheckout\\Infrastructure\\Adapter\\SystemConfiguration'] : ($this->services['PsCheckout\\Infrastructure\\Adapter\\SystemConfiguration'] = new \PsCheckout\Infrastructure\Adapter\SystemConfiguration())) && false ?: '_'}, ${($_ = isset($this->services['PsCheckout\\Infrastructure\\Adapter\\Configuration']) ? $this->services['PsCheckout\\Infrastructure\\Adapter\\Configuration'] : $this->load('getConfigurationService.php')) && false ?: '_'});
