<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PsCheckout\Presentation\Presenter\Settings\Admin\AdminSettingsPresenter' shared service.

return $this->services['PsCheckout\\Presentation\\Presenter\\Settings\\Admin\\AdminSettingsPresenter'] = new \PsCheckout\Presentation\Presenter\Settings\Admin\AdminSettingsPresenter([0 => ${($_ = isset($this->services['PsCheckout\\Presentation\\Presenter\\Settings\\Admin\\Modules\\ContextModule']) ? $this->services['PsCheckout\\Presentation\\Presenter\\Settings\\Admin\\Modules\\ContextModule'] : $this->load('getContextModuleService.php')) && false ?: '_'}, 1 => ${($_ = isset($this->services['PsCheckout\\Presentation\\Presenter\\Settings\\Admin\\Modules\\ConfigurationModule']) ? $this->services['PsCheckout\\Presentation\\Presenter\\Settings\\Admin\\Modules\\ConfigurationModule'] : $this->load('getConfigurationModuleService.php')) && false ?: '_'}, 2 => ${($_ = isset($this->services['PsCheckout\\Presentation\\Presenter\\Settings\\Admin\\Modules\\PaypalModule']) ? $this->services['PsCheckout\\Presentation\\Presenter\\Settings\\Admin\\Modules\\PaypalModule'] : $this->load('getPaypalModuleService.php')) && false ?: '_'}]);
