<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PsCheckout\Presentation\Presenter\Settings\Admin\Modules\ConfigurationModule' shared service.

return $this->services['PsCheckout\\Presentation\\Presenter\\Settings\\Admin\\Modules\\ConfigurationModule'] = new \PsCheckout\Presentation\Presenter\Settings\Admin\Modules\ConfigurationModule(${($_ = isset($this->services['ps_checkout.module']) ? $this->services['ps_checkout.module'] : $this->load('getPsCheckout_ModuleService.php')) && false ?: '_'}->id, ${($_ = isset($this->services['PsCheckout\\Infrastructure\\Adapter\\Configuration']) ? $this->services['PsCheckout\\Infrastructure\\Adapter\\Configuration'] : $this->load('getConfigurationService.php')) && false ?: '_'}, ${($_ = isset($this->services['PsCheckout\\Presentation\\Presenter\\FundingSource\\FundingSourcePresenter']) ? $this->services['PsCheckout\\Presentation\\Presenter\\FundingSource\\FundingSourcePresenter'] : $this->load('getFundingSourcePresenterService.php')) && false ?: '_'}, ${($_ = isset($this->services['PsCheckout\\Infrastructure\\Adapter\\Context']) ? $this->services['PsCheckout\\Infrastructure\\Adapter\\Context'] : ($this->services['PsCheckout\\Infrastructure\\Adapter\\Context'] = new \PsCheckout\Infrastructure\Adapter\Context())) && false ?: '_'}->getShop()->id);
