<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PsCheckout\Infrastructure\Bootstrap\Install\ConfigurationInstaller' shared service.

return $this->services['PsCheckout\\Infrastructure\\Bootstrap\\Install\\ConfigurationInstaller'] = new \PsCheckout\Infrastructure\Bootstrap\Install\ConfigurationInstaller(${($_ = isset($this->services['PsCheckout\\Infrastructure\\Repository\\ShopRepository']) ? $this->services['PsCheckout\\Infrastructure\\Repository\\ShopRepository'] : ($this->services['PsCheckout\\Infrastructure\\Repository\\ShopRepository'] = new \PsCheckout\Infrastructure\Repository\ShopRepository())) && false ?: '_'}, ${($_ = isset($this->services['PsCheckout\\Infrastructure\\Adapter\\Configuration']) ? $this->services['PsCheckout\\Infrastructure\\Adapter\\Configuration'] : $this->load('getConfigurationService.php')) && false ?: '_'});
