<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PsCheckout\Infrastructure\Bootstrap\Install\DatabaseTableInstaller' shared service.

return $this->services['PsCheckout\\Infrastructure\\Bootstrap\\Install\\DatabaseTableInstaller'] = new \PsCheckout\Infrastructure\Bootstrap\Install\DatabaseTableInstaller(${($_ = isset($this->services['ps_checkout.db']) ? $this->services['ps_checkout.db'] : $this->load('getPsCheckout_DbService.php')) && false ?: '_'});
