<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PsCheckout\Core\PaymentToken\Action\DeletePaymentTokenAction' shared service.

return $this->services['PsCheckout\\Core\\PaymentToken\\Action\\DeletePaymentTokenAction'] = new \PsCheckout\Core\PaymentToken\Action\DeletePaymentTokenAction(${($_ = isset($this->services['PsCheckout\\Infrastructure\\Repository\\PaymentTokenRepository']) ? $this->services['PsCheckout\\Infrastructure\\Repository\\PaymentTokenRepository'] : $this->load('getPaymentTokenRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['PsCheckout\\Api\\Http\\CheckoutHttpClient']) ? $this->services['PsCheckout\\Api\\Http\\CheckoutHttpClient'] : $this->load('getCheckoutHttpClientService.php')) && false ?: '_'}, ${($_ = isset($this->services['PsCheckout\\Infrastructure\\Adapter\\Configuration']) ? $this->services['PsCheckout\\Infrastructure\\Adapter\\Configuration'] : $this->load('getConfigurationService.php')) && false ?: '_'});
