<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PsCheckout\Presentation\Presenter\FundingSource\FundingSourceTranslationProvider' shared service.

return $this->services['PsCheckout\\Presentation\\Presenter\\FundingSource\\FundingSourceTranslationProvider'] = new \PsCheckout\Presentation\Presenter\FundingSource\FundingSourceTranslationProvider(${($_ = isset($this->services['PsCheckout\\Module\\Presentation\\Translator']) ? $this->services['PsCheckout\\Module\\Presentation\\Translator'] : $this->load('getTranslatorService.php')) && false ?: '_'});
