<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PsCheckout\Infrastructure\Bootstrap\Install\FundingSourceInstaller' shared service.

return $this->services['PsCheckout\\Infrastructure\\Bootstrap\\Install\\FundingSourceInstaller'] = new \PsCheckout\Infrastructure\Bootstrap\Install\FundingSourceInstaller(${($_ = isset($this->services['PsCheckout\\Infrastructure\\Repository\\ShopRepository']) ? $this->services['PsCheckout\\Infrastructure\\Repository\\ShopRepository'] : ($this->services['PsCheckout\\Infrastructure\\Repository\\ShopRepository'] = new \PsCheckout\Infrastructure\Repository\ShopRepository())) && false ?: '_'}, ${($_ = isset($this->services['PsCheckout\\Infrastructure\\Repository\\FundingSourceRepository']) ? $this->services['PsCheckout\\Infrastructure\\Repository\\FundingSourceRepository'] : $this->load('getFundingSourceRepositoryService.php')) && false ?: '_'});
