<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Monolog\Handler\HandlerInterface' shared service.

return $this->services['Monolog\\Handler\\HandlerInterface'] = ${($_ = isset($this->services['PsCheckout\\Infrastructure\\Logger\\LoggerHandlerFactory']) ? $this->services['PsCheckout\\Infrastructure\\Logger\\LoggerHandlerFactory'] : $this->load('getLoggerHandlerFactoryService.php')) && false ?: '_'}->build();
