<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PsCheckout\Infrastructure\Logger\LoggerFactory' shared service.

return $this->services['PsCheckout\\Infrastructure\\Logger\\LoggerFactory'] = new \PsCheckout\Infrastructure\Logger\LoggerFactory(${($_ = isset($this->services['ps_checkout.module']) ? $this->services['ps_checkout.module'] : $this->load('getPsCheckout_ModuleService.php')) && false ?: '_'}->name, ${($_ = isset($this->services['Monolog\\Handler\\HandlerInterface']) ? $this->services['Monolog\\Handler\\HandlerInterface'] : $this->load('getHandlerInterfaceService.php')) && false ?: '_'});
