<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PsCheckout\Infrastructure\Logger\LoggerFileReader' shared service.

return $this->services['PsCheckout\\Infrastructure\\Logger\\LoggerFileReader'] = new \PsCheckout\Infrastructure\Logger\LoggerFileReader(${($_ = isset($this->services['PsCheckout\\Infrastructure\\Adapter\\Validate']) ? $this->services['PsCheckout\\Infrastructure\\Adapter\\Validate'] : ($this->services['PsCheckout\\Infrastructure\\Adapter\\Validate'] = new \PsCheckout\Infrastructure\Adapter\Validate())) && false ?: '_'}, ${($_ = isset($this->services['PsCheckout\\Infrastructure\\Logger\\LoggerFileFinder']) ? $this->services['PsCheckout\\Infrastructure\\Logger\\LoggerFileFinder'] : $this->load('getLoggerFileFinderService.php')) && false ?: '_'});
