<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mbo.event_subscriber.module_event_subscriber' shared service.

return $this->services['mbo.event_subscriber.module_event_subscriber'] = new \PrestaShop\Module\Mbo\EventSubscriber\ModuleEventSubscriber(${($_ = isset($this->services['logger']) ? $this->services['logger'] : $this->getLoggerService()) && false ?: '_'}, ${($_ = isset($this->services['mbo.cdc.distribution_authentication_provider']) ? $this->services['mbo.cdc.distribution_authentication_provider'] : $this->load('getMbo_Cdc_DistributionAuthenticationProviderService.php')) && false ?: '_'}, ${($_ = isset($this->services['mbo.cdc.context_builder']) ? $this->services['mbo.cdc.context_builder'] : $this->load('getMbo_Cdc_ContextBuilderService.php')) && false ?: '_'}, ${($_ = isset($this->services['mbo.cdc.client.distribution_api']) ? $this->services['mbo.cdc.client.distribution_api'] : $this->load('getMbo_Cdc_Client_DistributionApiService.php')) && false ?: '_'});
