<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PsCheckout\Infrastructure\Bootstrap\Install\OrderStateInstaller' shared service.

return $this->services['PsCheckout\\Infrastructure\\Bootstrap\\Install\\OrderStateInstaller'] = new \PsCheckout\Infrastructure\Bootstrap\Install\OrderStateInstaller(${($_ = isset($this->services['PsCheckout\\Infrastructure\\Adapter\\Configuration']) ? $this->services['PsCheckout\\Infrastructure\\Adapter\\Configuration'] : $this->load('getConfigurationService.php')) && false ?: '_'}, ${($_ = isset($this->services['PsCheckout\\Infrastructure\\Adapter\\Language']) ? $this->services['PsCheckout\\Infrastructure\\Adapter\\Language'] : ($this->services['PsCheckout\\Infrastructure\\Adapter\\Language'] = new \PsCheckout\Infrastructure\Adapter\Language())) && false ?: '_'}, ${($_ = isset($this->services['ps_checkout.module']) ? $this->services['ps_checkout.module'] : $this->load('getPsCheckout_ModuleService.php')) && false ?: '_'}->name);
