<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PsCheckout\Core\PayPal\Order\Provider\PayPalOrderProvider' shared service.

return $this->services['PsCheckout\\Core\\PayPal\\Order\\Provider\\PayPalOrderProvider'] = new \PsCheckout\Core\PayPal\Order\Provider\PayPalOrderProvider(${($_ = isset($this->services['PsCheckout\\Infrastructure\\Adapter\\Configuration']) ? $this->services['PsCheckout\\Infrastructure\\Adapter\\Configuration'] : $this->load('getConfigurationService.php')) && false ?: '_'}, ${($_ = isset($this->services['PsCheckout\\Core\\PayPal\\Order\\Cache\\PayPalOrderCache']) ? $this->services['PsCheckout\\Core\\PayPal\\Order\\Cache\\PayPalOrderCache'] : $this->load('getPayPalOrderCacheService.php')) && false ?: '_'}, ${($_ = isset($this->services['PsCheckout\\Infrastructure\\Repository\\PayPalOrderRepository']) ? $this->services['PsCheckout\\Infrastructure\\Repository\\PayPalOrderRepository'] : $this->load('getPayPalOrderRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['PsCheckout\\Api\\Http\\OrderHttpClient']) ? $this->services['PsCheckout\\Api\\Http\\OrderHttpClient'] : $this->load('getOrderHttpClientService.php')) && false ?: '_'});
